### ISSUE TITLE
可以获取用户信息吗

### ISSUE THREAD

**Issue by lovesnacks** [QinY-Stat/WeiboSpider#1]
您好，请问可以把用户的个人信息如性别/所在地/出生年月等标签一起爬取下来吗

**Comment by qinyuenlp** [comment]
您好，您是说爬取用户在其主页填写的个人信息吗？目前上传的代码是无法完成这个工作的。
事实上您说的这个工作我已经写了一部分了，但还没有全部完成，过段时间会上传。

**Comment by lovesnacks** [comment]
是的是的！谢谢您的回复～

**Comment by lovesnacks** [comment]
您好，您运行user spider有出现这样的情况吗？就是弹出chrome微博页面登陆，自动输入用户名和密码，我手动输入验证码然后确认就没有下一步了，就会报错。大概有两种错误：
1）selenium.common.exceptions.TimeoutException: Message:
2）selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'url' must be a string
![image](https://user-images.githubusercontent.com/41772072/57121697-c09f2080-6dab-11e9-9e9c-6ffb44944005.png)
![image](https://user-images.githubusercontent.com/41772072/57121741-f6440980-6dab-11e9-9c4e-9a6e4113527f.png)

**Comment by qinyuenlp** [comment]
我这里是没有出现这两个情况的，第一个TimeoutException可能的情况比较多，不太好分析；第二个错误说url不是字符，您可以检查一下输入的href是否正确。
