### ISSUE TITLE
可以爬取固定时间内发表的微博吗

### ISSUE THREAD

**Issue by lovesnacks** [QinY-Stat/WeiboSpider#2]
您好，现在的代码获取某关键字下搜到的微博是从时间最新的开始，而且搜索结果好像只有50页，那是不是意味着50页以前的就无法爬取了呢？如果我想获得固定时间段的微博比如2018年间的，可以对这个代码进行修改吗？我看了一下好像很多地方都和最近时间latest相关，好像不太好改，请教您一下。

**Comment by qinyuenlp** [comment]
您好，
1.由于新浪微博官方的设置问题，搜索结果最多只有50页；
2.想要爬取50页之前某一固定时间段的结果需要调用微博的‘高级搜索’功能来实现，目前的代码里是没有这个功能的；
3.latest主要出现在文件的更新部分中，这是为了避免程序在后台实时爬取最新消息时往文件中写入重复内容。如果只是想搜索固定时间段的微博，那您只需要执行[爬取-保存]过程即可，不需要更新文件，所以也不会涉及到latest。

**Comment by qinyuenlp** [comment]
您好，目前已经可以爬取指定时间段的微博关键词搜索结果了，但由于微博限制，最多只能爬取指定时间区间内的前50页。

**Comment by lovesnacks** [comment]
好的！谢谢您
